swagger: '2.0'

info:
  version: "0.0.1"
  title: radio.co Client
  
host: public.radio.co
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /stations/{stationId}/status:
    get:
      operationId: getStatus
      description: |
        Gets Status of the given station
      parameters:
        -
          name: stationId
          in: path
          description: Given station id
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/StationStatusDto'
              
definitions:
  CurrentTrackDto:
    type: object
    properties:
      title:
        type: string

  HistoryTrackDto:
    type: object
    properties:
      title:
        type: string
      
  StationStatusDto:
    type: object
    properties:
      status:
        type: string
      logo_url:
        type: string
      current_track:
        $ref: '#/definitions/CurrentTrackDto'
      history:
        type: array
        items:
          $ref: '#/definitions/HistoryTrackDto'
