/**
 * radio.co Client
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.radiococlient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.mallorcasoftware.radiococlient.model.CurrentTrackDto;
import com.mallorcasoftware.radiococlient.model.HistoryTrackDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * StationStatusDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-15T22:56:31.480+02:00")
public class StationStatusDto   {
  @SerializedName("status")
  private String status = null;

  @SerializedName("logo_url")
  private String logoUrl = null;

  @SerializedName("current_track")
  private CurrentTrackDto currentTrack = null;

  @SerializedName("history")
  private List<HistoryTrackDto> history = new ArrayList<HistoryTrackDto>();

  public StationStatusDto status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public StationStatusDto logoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Get logoUrl
   * @return logoUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLogoUrl() {
    return logoUrl;
  }

  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  public StationStatusDto currentTrack(CurrentTrackDto currentTrack) {
    this.currentTrack = currentTrack;
    return this;
  }

   /**
   * Get currentTrack
   * @return currentTrack
  **/
  @ApiModelProperty(example = "null", value = "")
  public CurrentTrackDto getCurrentTrack() {
    return currentTrack;
  }

  public void setCurrentTrack(CurrentTrackDto currentTrack) {
    this.currentTrack = currentTrack;
  }

  public StationStatusDto history(List<HistoryTrackDto> history) {
    this.history = history;
    return this;
  }

  public StationStatusDto addHistoryItem(HistoryTrackDto historyItem) {
    this.history.add(historyItem);
    return this;
  }

   /**
   * Get history
   * @return history
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<HistoryTrackDto> getHistory() {
    return history;
  }

  public void setHistory(List<HistoryTrackDto> history) {
    this.history = history;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StationStatusDto stationStatusDto = (StationStatusDto) o;
    return Objects.equals(this.status, stationStatusDto.status) &&
        Objects.equals(this.logoUrl, stationStatusDto.logoUrl) &&
        Objects.equals(this.currentTrack, stationStatusDto.currentTrack) &&
        Objects.equals(this.history, stationStatusDto.history);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, logoUrl, currentTrack, history);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StationStatusDto {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    currentTrack: ").append(toIndentedString(currentTrack)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

